# Generated by Django 2.0.7 on 2018-07-17 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180716_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='dni',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Company dni'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='company',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
    ]
